"""empty message

Revision ID: ebf728dc4d0d
Revises: 51f5ccfba190
Create Date: 2017-05-31 14:31:13.504000

"""

# revision identifiers, used by Alembic.
revision = 'ebf728dc4d0d'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
